braintree/browser-switch-android

browser-switch/src/main/java/com/braintreepayments/browserswitch/ChromeCustomTabs.java

If you switch to a password manager or try to use something like 1Password's password keyboard, the Chrome Custom Tab is killed as a result of the Intent flags specified and the user has to start the flow over from the beginning.
This opts to leave the Chrome Custom Tab around rather than break or degrade flows for password managers or multitasking. This does make it possible for the user to revisit the Chrome Custom Tab after they've finished their browser switch and switch back to the app again causing a weird switch back where nothing happens. This odd behavior can be mitigated by the page that returns the user to the app by displaying a page that says everything is complete and removing the button/link that switches back to the app.

Prevent Chrome Custom Tab from being killed when user leaves

---

browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchFragmentTest.java

Fixes #4 
Adds a check to ensure that there is at least one activity available to handle the browser intent.
cc:
@quinnjn 
@bluk

Return error when no activities are available to handle browser intent

---

browser-switch/build.gradle
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchActivity.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchFragmentTest.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/test/TestActivity.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/test/TestBrowserSwitchFragment.java
build.gradle
demo/build.gradle
demo/src/main/java/com/braintreepayments/browserswitch/demo/DemoActivity.java
demo/src/main/java/com/braintreepayments/browserswitch/demo/DemoFragment.java

Android P will deprecate `android.app.Fragment`. This PR adds support for the support fragment `androidx.fragment.app.Fragment`
This PR includes:
* **Breaking Change**: Move BrowserSwitchFragment from `android.app.Fragment` to `androidx.fragment.app.Fragment`
* Update Android Plugin for Gradle to 3.1.4
* Uses `androidx` support libraries
* Updating to SDK 28

**Breaking Changes** Migrate to support fragments

---

browser-switch/build.gradle
browser-switch/src/main/java/com/braintreepayments/browserswitch/ChromeCustomTabs.java

When Jetifier transforms imports for AndroidX it misses the Intent changes for Chrome Custom Tabs because they are hardcoded. 
Using the import should properly transform the imports for AndroidX.

Jetifier wont transform hardcoded imports

---

README.md

Issue reported here: https://github.com/braintree/braintree_android/issues/236
Activities that have a `singleInstance` launch mode (i.e. Activity launching on its own activity stack) will start Activities on a different activity stack which prevents Browser Switch from returning a result.

Doc singleInstance activities and browser-switch

---

README.md

There have been queries on why browser-switch requires lowercase letters. It is because the Android framework considers schemes case ~~insensitive~~ sensitive.

Link to scheme matching Android docs

---

demo/src/main/java/com/braintreepayments/browserswitch/demo/DemoActivity.java

Steps to reproduce the issue:
* Add a log to `BrowserSwitchFragment.onResume()`:
```
Log.d("BrowserSwitchFragment","onResume " + this);
```
* Build and install the app
* Launch the app
* Monitor logcat
* Rotate the device multiple times
* Expected behavior: Each time you rotate, you only see one additional log like:
```
04-17 11:26:24.201 30906 30906 D BrowserSwitchFragment: onResume DemoFragment{f089136 #0 id=0x1020002}
```
* Actual behavior: Each time you rotate, the number of additional `onResume` logs increases. 1 rotation = 2 additional logs, 2 rotations = 3 additional logs, 3 rotations = 4 additional logs, etc.
To fix this, only add the fragment if `savedInstanceState` is null. We know the fragment will already be present if `savedInstanceState` is not null, because the …

Prevent multiple DemoFragment instances from being created

---

CHANGELOG.md
browser-switch/build.gradle
browser-switch/src/androidTest/java/com/braintreepayments/browserswitch/ChromeCustomTabsTest.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchOptions.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchPersistentStore.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchRequest.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchResult.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchClientTest.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchFragmentTest.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchPersistentStoreTest.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchRequestTest.java
demo/build.gradle
demo/src/androidTest/java/com/braintreepayments/browserswitch/demo/BrowserSwitchTest.java
demo/src/main/java/com/braintreepayments/browserswitch/demo/DemoFragment.java
demo/src/main/res/layout/demo_fragment.xml
demo/src/main/res/values/strings.xml

- Create `BrowserSwitchOptions` value object for configuring browser switch behavior
- Add BrowserSwitchClient#start overloads with `BrowserSwitchOptions` param
- Add BrowserSwitchFragment#browserSwitch overload with `BrowserSwitchOptions` param
- @sarahkoop @sshropshire

Request Metadata via BrowserSwitchOptions

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchFragment.java

- Fix BrowserSwitchFragment NPE when `getReturnUrlScheme` is called and an Activity is no longer attached to the fragment.
- @sarahkoop 
- @sshropshire

Fix BrowserSwitchFragment Null Pointer in `getReturnUrlScheme` method

---

.travis.yml
CHANGELOG.md
README.md
browser-switch/build.gradle
browser-switch/src/main/AndroidManifest.xml
browser-switch/src/test/resources/robolectric.properties
build.gradle
demo/build.gradle
demo/src/androidTest/java/com/braintreepayments/browserswitch/demo/BrowserSwitchTest.java
gradle/wrapper/gradle-wrapper.properties

- Update to SDK version 30
- Add `query` section to AndroidManifest to allow querying for web browsers on a device
- Eliminate snapshot builds
- @sarahkoop 
- @sshropshire

Compile for Android 11

---

CHANGELOG.md
README.md
browser-switch/src/main/AndroidManifest.xml
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchException.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchInspector.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchListener.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchOptions.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchPersistentStore.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchRequest.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchResult.java
browser-switch/src/main/java/com/braintreepayments/api/PersistentStore.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchInspectorUnitTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchPersistentStoreUnitTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchRequestUnitTest.java
browser-switch/src/test/java/com/braintreepayments/api/PersistentStoreUnitTest.java
demo/src/androidTest/java/com/braintreepayments/api/demo/BrowserSwitchTest.java
demo/src/main/AndroidManifest.xml
demo/src/main/java/com/braintreepayments/api/demo/DemoActivity.java
demo/src/main/java/com/braintreepayments/api/demo/DemoFragment.java

-   * Move BrowserSwitch module from `com.braintreepayments.browserswitch` package to `com.braintreepayments.api` 
- @sarahkoop 
- @sshropshire

Move BrowserSwitch to com.braintreepayments.api

---

browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchInspector.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchRequest.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchResult.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchRequestUnitTest.java
demo/src/main/java/com/braintreepayments/api/demo/DemoFragment.java

- Rename internal variables including `uri` to `url` for consistency and to match public accessor methods
- ~[ ] Added a changelog entry~
- @sarahkoop

Rename Uri Variables to Url

---

browser-switch/build.gradle

- Fix an issue that caused javadocs and source jars to be omitted from `maven-publish` artifacts
~- [ ] Added a changelog entry~
- @sarahkoop 
- @sshropshire

Add SourcesJar and JavadocsJar to Maven Publish

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchInspector.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchInspectorUnitTest.java

- Change `canDeviceOpenUrl` method to `deviceHasBrowser` to fix an issue where app links couldn't be opened
- @sshropshire 
- @sarahkoop

Add deviceHasBrowser Check

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/browserswitch/ActivityFinder.java
browser-switch/src/main/java/com/braintreepayments/browserswitch/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/ActivityFinderTest.java
browser-switch/src/test/java/com/braintreepayments/browserswitch/BrowserSwitchClientTest.java

- Change `canOpenUrl` method to `deviceHasBrowser` to fix an issue where app links couldn't be opened
- @sshropshire 
- @sarahkoop

Add deviceHasBrowser Check v1

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchOptions.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchRequest.java
browser-switch/src/main/java/com/braintreepayments/api/PersistentStore.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientTest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchRequestUnitTest.java
demo/src/main/java/com/braintreepayments/api/demo/DemoFragment.java

- Update `BrowserSwitchClient#deliverResult()` to allow canceled browser switches a chance to reach the success state (See braintree_android [#409](https://github.com/braintree/braintree_android/issues/409))
- Fix nullability annotations in `BrowserSwitchOptions` setters
- Fix shared preferences key typo
- @sestevens 
- @sshropshire

BrowserSwitchRequest Should Notify Cancellation

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
browser-switch/src/test/java/com/braintreepayments/api/ChromeCustomTabsInternalClientUnitTest.java

- Add `getResult()` method to `BrowserSwitchClient` to allow "previews" of a pending browser switch result before it is delivered.
- Rename `BrowserSwitchClientTest` to `BrowserSwitchClientUnitTest`
- Rename `ChromeCustomTabsInternalClientTest` to `ChromeCustomTabsInternalClientUnitTest`
- `getResult()` method already has full test coverage through `deliverResult()`
- @sshropshire

Get Browser Switch Result

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java

* Add BrowserSwitchClient#getResult() method to peek at a pending browser switch result before it is delivered
* Add BrowserSwitchClient#getResultFromCache() method to peek at a cached browser switch result before it is delivered
- @jaxdesmarais 
- @sshropshire

Make Get Result Methods Public

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java

- Fix issue that causes successful deep links to be parsed multiple times
- @mattwylder
- @sshropshire

Prevent Browser Switch Results From Being Parsed Twice

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java

- Check if a pending browser switch request exists before delivering a browser switch result instead of setting Activity intent to `null` (fix for #634)
- @sshropshire

Keep Activity Intent After Successful Browser Switch

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java

- Fix issue that causes a browser switch to start while the host Activity is finishing.
- @sshropshire

Check if Activity is Finishing Before Browser Switch

---

CHANGELOG.md
gradle.properties

- Removing Jetifier from project. We are fully migrated onto `androidx.*`
- @sshropshire

Remove Jetifier From Project

---

CHANGELOG.md
browser-switch/build.gradle
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
build.gradle

* Upgrade `compileSdkVersion` and `targetSdkVersion` to API 33
* Remove unnecessary assertion for a browser application on the device
- @sshropshire

Remove Browser Check and Officially Support API Version 33

---

CHANGELOG.md
browser-switch/build.gradle
build.gradle
demo/build.gradle
gradle/wrapper/gradle-wrapper.properties

- Remove Kotlin BOM platform dependency
- Revert `androidx.annotation:annotation` dependency to version `1.2.0`
- Revert `androidx.appcompat:appcompat` dependency to version `1.3.1`
- @sshropshire

Remove Kotlin BOM

---

.github/workflows/release.yml
CHANGELOG.md
browser-switch/build.gradle
build.gradle
ci
gradle.properties
gradle/gradle-publish.gradle

Thank you for your contribution to Braintree. 
- Update to use [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) which is the replacement for the no longer maintained [Nexus Publish Plugin](https://github.com/marcphilipp/nexus-publish-plugin).
- This change has been tested through the publish staging repository step. The close and release repository step can't be tested until we are ready to release a new version of the SDK.
- ~[ ] Added a changelog entry~
- @sarahkoop

Update to use Gradle Nexus Publish Plugin

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java

- Catch the `ActivityNotFoundException` that is thrown in `BrowserSwitchClient#start` when a browser app is not available, and throw a `BrowserSwitchException` as defined by the method contract
- Will be used to resolve [issue in core SDK](https://github.com/braintree/braintree_android/issues/799)
- @sarahkoop

Throw BrowserSwitchException When Unable to Start Activity

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchPendingRequest.kt
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchRequest.java
browser-switch/src/main/java/com/braintreepayments/api/ChromeCustomTabsInternalClient.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
gradle/gradle-publish.gradle

- Add `BrowserSwitchClient.start` method that returns a `BrowserSwitchRequest` to allow integrators to store the pending request locally and pass it to new `BrowserSwithClient.parseResult` method to deliver browser switch results.
- Remove storing pending requests in shared preferences in favor of allowing integrators to store the pending requests within their own app in whatever way works best for their architecture - this allows integrators to check if they have an existing pending request (i.e. they've launched a browser switch), before trying to fetch a result. The effect is that if they have a pending request, but don't receive a result, they can infer that the browser switch was cancelled or not completed and can handle accordingly. 
- See this [draft …

Add Integration Pattern without Local Storage

---

.github/actions/setup_java/action.yml
.github/workflows/static_analysis.yml
.github/workflows/tests.yml
CHANGELOG.md
browser-switch/build.gradle
browser-switch/src/main/AndroidManifest.xml
build.gradle
demo/build.gradle
demo/src/main/AndroidManifest.xml
gradle.properties
gradle/wrapper/gradle-wrapper.properties

- Upgrade gradle dependencies to latest (and align with BT Core SDK versions)
- Bump Java version to 11 and Kotlin to 1.9.10
- Upgrade to Android Gradle Plugin 8 (aligns with core)
- Bump min SDK version to 23 - there isn't anything specific in this SDK that requires the min version bump, but this gives us more flexibility and aligns with the Core v5 min SDK version
- @sarahkoop

Upgrade Gradle Dependencies

---

gradle/gradle-publish.gradle

- Fix javadocs task breaking SNAPSHOT publishing when using AGP 8
- ~[ ] Added a changelog entry~
- @sarahkoop

Fix Javadocs Task for SNAPSHOT Publish

---

README.md
build.gradle

- Update gradle release tasks to allow for releasing beta versions with format `3.0.0-beta1`
- ~[ ] Added a changelog entry~
- @sarahkoop

Update Gradle Release Tasks for Beta

---

browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/res/values/strings.xml
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java

- Update `assertCanPerformBrowserSwitch` in `BrowserSwitchClient` to accommodate `BrowserSwitchOptions.appLinkUri`
-

Update assertCanPerformBrowserSwitch to accommodate app links

---

demo/src/main/java/com/braintreepayments/api/demo/DemoFragment.java
demo/src/main/res/layout/demo_fragment.xml
demo/src/main/res/values/arrays.xml
demo/src/main/res/values/strings.xml

- Add deep link / app link toggle to `DemoFragment`
- Configure app link flow using `https://mobile-sdk-demo-site-838cead5d3ab.herokuapp.com` url
Related popup bridge PR: https://github.com/braintree/popup-bridge-example/pull/10
-

Demo App - Add App Link toggle to DemoFragment

---

browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchRequest.java
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchRequestUnitTest.java

- Handle when `BrowserSwitchResult` has a null `returnUrlScheme` for the App Link flow
- Update `matchesAppLinkUri` logic to only check for a matching host and scheme
https://github.com/braintree/browser-switch-android/assets/5005216/54645fba-acaf-4ed8-9305-e0b89e6733fd
-

Handle when BrowserSwitchResult has a null returnUrlScheme and update matchesAppLinkUri logic

---

CHANGELOG.md
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchPendingRequest.kt
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchResult.kt
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
demo/src/main/java/com/braintreepayments/api/demo/ComposeActivity.kt
demo/src/main/java/com/braintreepayments/api/demo/DemoActivitySingleTop.java
v3_MIGRATION_GUIDE.md

- Rename `parseResult()` to `completeRequest()`
-

Rename parseResult to completeRequest

---

browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchStartResult.kt
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/ComposeActivity.kt
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/DemoActivitySingleTop.java
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/utils/PendingRequestStore.kt

- Rename `BrowserSwitchStartResult.Success` to `BrowserSwitchStartResult.Started`
~- [ ] Added a changelog entry~
- @sshropshire

[V3] Rename BrowserSwitchStartResult `.Success` to `.Started`

---

build.gradle

- Fix v3 migration guide file name in changeMigrationGuideVersion gradle task
-

Fix v3 migration guide file name

---

.github/workflows/release.yml
.github/workflows/temp_post_release.yml

Thank you for your contribution to Braintree. 
- Add a temporary workflow to run the `bump_version` and `create_github_release` jobs which were not run for the 3.0.0-beta1 release
-

Add Temp Post Release workflow

---

CHANGELOG.md
browser-switch/build.gradle
build.gradle
demo/build.gradle
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/ComposeActivity.kt
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/DemoActivitySingleTop.java
demo/src/main/java/com/braintreepayments/api/browserswitch/demo/MainActivity.java
demo/src/main/res/layout/activity_main.xml
demo/src/main/res/layout/demo_fragment.xml
demo/src/main/res/values/styles.xml
gradle/wrapper/gradle-wrapper.properties

- This PR upgrades `compileSdkVersion` and `targetSdkVersion` to API 35
- This PR also updates the Demo to support edge-to-edge displays
- @sshropshire

Support Android 15

---

CHANGELOG.md
browser-switch/build.gradle
build.gradle
demo/build.gradle

- Revert changes that require Java 17 in this SDK to allow merchants using Java 11 to integrate
- Keep Java 17 usage for CI and internal build tools, but update to compile SDK for Java 11 (see [Android docs](https://developer.android.com/build/jdks) for additional info on Java usage in Android)
- This change will be followed by similar change in the core SDK to support Java 11
- @sarahkoop

Downgrade to Support Java 11

---

CHANGELOG.md
browser-switch/build.gradle
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchClient.java
browser-switch/src/main/java/com/braintreepayments/api/BrowserSwitchOptions.java
browser-switch/src/main/java/com/braintreepayments/api/ChromeCustomTabsInternalClient.java
browser-switch/src/main/java/com/braintreepayments/api/LaunchType.kt
browser-switch/src/test/java/com/braintreepayments/api/BrowserSwitchClientUnitTest.java
browser-switch/src/test/java/com/braintreepayments/api/ChromeCustomTabsInternalClientUnitTest.kt
build.gradle

- Create new `LaunchType` enum that sets either `Intent.FLAG_ACTIVITY_NEW_TASK` or `Intent.FLAG_ACTIVITY_CLEAR_TOP` on the `CustomTabsIntent`
- Updated `BrowserSwitchOptions` builder to accept `LaunchType`
- Deprecated `launchAsNewTask` boolean in `BrowserSwitchOptions`
- Added mockk dependency
-

Add ability to set Intent.FLAG_ACTIVITY_CLEAR_TOP on the CustomTabsIntent
